funcs:
  scoreMelodicMotifs: [10, 40, 120]
  scoreRhythmicMotifs: [0.5, 2, 4.5]
  scoreOverlap: [0.7, 0.85, 0.95]
  scoreTonality: [0.6, 0.8, 0.95]
  scoreSimultaneousIntervals: [-0.2, 0.3, 0.6]
  scoreMeasureForChord: [0.2, 0.5, 0.8]
  scoreGridness16th: [0.5, 0.8, 0.95]
  scoreMusicLength: [0.2, 0.5, 0.7] #gebruiken we niet
  scoreNoteLengthDiversity: [0.3, 0.7, 0.9]
  scoreVoiceDensity : [0.3, 0.6, 0.9]
  scoreNoteDistribution: [0.2, 0.5, 0.7] # gebruiken we niet
  scoreBpm: [-15, -5, -0.1]
  scoreEnergyWaves: [-3.5, -1.5, -0.5]
  scoreMaxGap: [-1.5, -0.5, -0.1]
  scoreVelocityDiversity: [0.3, 0.7, 0.9]
  scorePitchClassDiversity: [0.2, 0.5, 0.7] #gebruiken we niet
  scoreGrowth: [0.2, 0.5, 0.7] #mag niet meetellen???