funcs:
  scoreMelodicMotifs: [10, 40, 120]
  scoreRhythmicMotifs: [0.5, 2, 4.5]
  scoreOverlap: [0.7, 0.85, 0.95]
  scoreTonality: [0.2, 0.5, 0.7]
  scoreSimultaneousIntervals: [0.2, 0.5, 0.7]
  scoreMeasureForChord: [0.2, 0.5, 0.7]
  scoreGridness16th: [0.2, 0.5, 0.7]
  scoreMusicLength: [0.2, 0.5, 0.7]
  scoreNoteLengthDiversity: [0.2, 0.5, 0.7]
  scoreVoiceDensity : [0.2, 0.5, 0.7]
  scoreNoteDistribution: [0.2, 0.5, 0.7]
  scoreBpm: [0.2, 0.5, 0.7]
  scoreEnergyWaves: [0.2, 0.5, 0.7]
  scoreMaxGap: [0.2, 0.5, 0.7]
  scoreVelocityDiversity: [0.2, 0.5, 0.7]
  scorePitchClassDiversity: [0.2, 0.5, 0.7]
  scoreGrowth: [0.2, 0.5, 0.7]