funcs:
  scoreMelodicMotifs: [0.2, 0.5, 0.7]
  scoreRhythmicMotifs: [0.2, 0.5, 0.7]
  scoreOverlap: [0.2, 0.5, 0.7]
  scoreTonality: [0.2, 0.5, 0.7]
  scoreSimultaneousIntervals: [0.2, 0.5, 0.7]
  scoreMeasureForChord: [0.2, 0.5, 0.7]
  scoreGridness16th: [0.2, 0.5, 0.7]
  scoreMultiple: [0.2, 0.5, 0.7]
  scoreMusicLength: [0.2, 0.5, 0.7]
  scoreNoteLengthDiversity: [0.2, 0.5, 0.7]
  scoreGrowthDensity: [0.2, 0.5, 0.7]
  scoreNoteDistribution: [0.2, 0.5, 0.7]
  scoreBpm: [0.2, 0.5, 0.7]
  scoreEnergyWaves: [0.2, 0.5, 0.7]
  scoreMaxGap: [0.2, 0.5, 0.7]