bpm: 95.0

# range 0--84 (is actual midi notes 24 - 108)
voices:
  min: 30
  max: 60

x_gens: 100
children: 100

modFuncs:
  - name: scoreMelodicMotifs
    weight: 0
    weightCC: 1
    params: []
    voices: [true, true, true]
    voicesCC: 114
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    splitVoicesCC: 28
    scoreRange: [0, null]

  - name: scoreRhythmicMotifs
    weight: 0
    weightCC: 2
    params: []
    voices: [true, true, true]
    voicesCC: 115
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    splitVoicesCC: 29
    scoreRange: [0, null]

  - name: scoreOverlap
    weight: 0
    weightCC: 3
    params:
      - name: "Target overlap bass"
        range: [0, 8]
        value: 0
        type: int
        cc: 11
      - name: "Target overlap mid"
        range: [0, 8]
        value: 3
        type: int
        cc: 12
      - name: "Target overlap high"
        range: [0, 8]
        value: 0
        type: int
        cc: 13
    voices: [true, true, true]
    voicesCC: 116
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    splitVoicesCC: 30
    scoreRange: [null, 1]

  - name: scoreTonality
    weight: 2
    weightCC: 4
    params:
      - name: Enabled scales
        range: [0, 64]
        value: 33
        # 000001 == 1 == "major"
        # 000010 == 2 == "minor"
        # 000100 == 4 == "altered_pent"
        # 001000 == 8 == "whole_tone"
        # 010000 == 16 == "lydian"
        # 100000 == 32 == "major_pentatonic"
        type: int
        cc: 101
    voices: [true, true, true]
    voicesCC: 117
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: true
    splitVoices: false
    splitVoicesCC: 32
    scoreRange: [-1, 1]

  - name: scoreSimultaneousIntervals
    weight: 0
    weightCC: 5
    params: []
    voices: [false, true, false]
    voicesCC: 118
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: true
    splitVoices: false
    splitVoicesCC: 33
    scoreRange: [-1, 1]

  - name: scoreMeasureForChord
    weight: 0
    weightCC: 6
    params:
      - name: Chord categories
        range: [0, 64]
        value: 8
          # 000001 = 1 = tonal_core
          # 000010 = 2 = open_modal
          # 000100 = 4 = rich_tertian
          # 001000 = 8 = altered_expressive
          # 010000 = 16 = symmetrical_tension
          # 100000 = 32 = clusters
        type: int
        cc: 103
      - name: Optimum
        range: [0, 1]
        value: 1
        type: float
        cc: 113
    voices: [true, true, true]
    voicesCC: 119
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: true
    splitVoices: false
    splitVoicesCC: 34
    scoreRange: [-1, 1]

  - name: scoreGridness16th
    weight: 2
    weightCC: 7
    params:
      - name: Optimum
        range: [0, 1]
        value: 1
        type: float
        cc: 14
      - name: Enabled grids
        range: [0, 8]
        value: 7
        # 001 == 1 == 8
        # 010 == 2 == 16
        # 011 == 3 == 8,16
        # 100 == 4 == 8t
        # 101 == 5 == 8,8t
        # 110 == 6 == 16,8t
        # 111 == 7 == 8,16,8t
        type: int
        cc: 100
    voices: [true, true, true]
    voicesCC: 120
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: true
    splitVoices: false
    splitVoicesCC: 35
    scoreRange: [-1, 1]

  - name: scoreMusicLength
    weight: 1
    weightCC: 8
    params:
      - name: "Q Note count"
        range: [0, 127]
        value: 8
        type: int
        cc: 15
    voices: [true, true, true]
    voicesCC: 121
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    splitVoicesCC: 36
    scoreRange: [null, 0]

  - name: scoreNoteLengthDiversity
    weight: 0
    weightCC: 9
    params:
      - name: "Target diversity"
        range: [0, 1]
        value: 0
        type: float
        cc: 16
      - name: "Note length preference"
        range: [0, 1]
        value: 0.5
        type: float
        cc: 17
    voices: [true, true, true]
    voicesCC: 122
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: true
    splitVoices: false
    splitVoicesCC: 37
    scoreRange: [-1, 1]

  - name: scoreGrowthDensity
    weight: 1
    weightCC: 10
    params:
      - name: "Target density bass"
        range: [0, 8]
        value: 1
        type: float
        cc: 18
      - name: "Target density mid"
        range: [0, 8]
        value: 4
        type: float
        cc: 19
      - name: "Target density high"
        range: [0, 8]
        value: 1
        type: float
        cc: 20
    voices: [true, true, true]
    voicesCC: 123
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    splitVoicesCC: 38
    scoreRange: [null, 0]
  - name: scoreNoteDistribution
    weight: 1
    weightCC: 11
    params:
      - name: "Optimum"
        range: [-1, 1] # -1 clustered,  1 fully even
        value: 0.5
        type: float
        cc: 21
    voices: [true, true, true]
    voicesCC: 124
    normalizationFunc: none
    hasNormalizedScore: true
    splitVoices: false
    splitVoicesCC: 39
    scoreRange: [-1, 1]
  - name: scoreBpm
    weight: 2
    weightCC: 105
    params:
      - name: "Optimum"
        range: [50, 200]
        value: 55
        type: float
        cc: 22
    voices: [true, true, true]
    voicesCC: 125
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    splitVoicesCC: 40
    scoreRange: [-1, 1]
  - name: scoreEnergyWaves
    weight: 5
    weightCC: 107
    params:
      - name: MinVar
        range: [0, 10]
        value: 8
        type: float
        cc: 23
      - name: MaxVar
        range: [0, 10]
        value: 10
        type: float
        cc: 24
      - name: beatsPerMeasure
        range: [2, 8]
        value: 2
        type: int
        cc: 25
      - name: stepBeats
        range: [0.25, 2]
        value: 0.5
        type: int
        cc: 26
      - name: onsetMergeSubdivision
        range: [8, 128]
        value: 64
        type: int
        cc: 27
    voices: [true, true, true]
    voicesCC: 126
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    splitVoicesCC: 41
    scoreRange: [null, 1]
  - name: scoreMaxGap
    weight: 0
    weightCC: 105
    params:
      - name: "maxGapBeats"
        range: [0.1, 10]
        value: 3
        type: float
        cc: 28
    voices: [true, true, true]
    voicesCC: 126
    normalizationFunc: normalizeMinOneToOne
    hasNormalizedScore: false
    splitVoices: false
    splitVoicesCC: 41
    scoreRange: [null, 0]
