cc: 1
value: 127
funcs:
  scoreBpm:
    weight: linear
    params:
    - linear
  scoreGridness16th:
    weight: linear
    params:
    - linear
    - none
    - none
  scoreRhythmicMotifs:
    weight: linear
    params: []
steps:
  1:
    scoreBpm:
      weight: 1.0
      params:
      - 70.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreGridness16th:
      weight: 3.0
      params:
      - 0.2
      - 1.0
      - 0.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreRhythmicMotifs:
      weight: 0.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: false
  2:
    scoreBpm:
      weight: 1.0
      params:
      - 80.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreGridness16th:
      weight: 3.0
      params:
      - 0.1
      - 2.0
      - 0.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreRhythmicMotifs:
      weight: 0.5
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: false
  3:
    scoreBpm:
      weight: 1.0
      params:
      - 90.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreGridness16th:
      weight: 3.0
      params:
      - 0.05
      - 2.0
      - 0.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreRhythmicMotifs:
      weight: 1.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: false
  4:
    scoreBpm:
      weight: 1.0
      params:
      - 90.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreGridness16th:
      weight: 3.0
      params:
      - 0.3
      - 4.0
      - 0.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreRhythmicMotifs:
      weight: 1.0
      params: []
      voices:
      - false
      - false
      - true
      splitVoices: true
  5:
    scoreBpm:
      weight: 1.0
      params:
      - 100.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreGridness16th:
      weight: 3.0
      params:
      - 0.3
      - 4.0
      - 0.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreRhythmicMotifs:
      weight: 1.5
      params: []
      voices:
      - true
      - false
      - true
      splitVoices: true
  6:
    scoreBpm:
      weight: 1.0
      params:
      - 120.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreGridness16th:
      weight: 3.0
      params:
      - 0.1
      - 4.0
      - 0.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreRhythmicMotifs:
      weight: 1.5
      params: []
      voices:
      - true
      - false
      - true
      splitVoices: true
  7:
    scoreBpm:
      weight: 1.0
      params:
      - 120.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreGridness16th:
      weight: 3.0
      params:
      - 0.1
      - 7.0
      - 0.0
      voices:
      - true
      - true
      - true
      splitVoices: true
    scoreRhythmicMotifs:
      weight: 0.5
      params: []
      voices:
      - true
      - false
      - true
      splitVoices: true
  8:
    scoreBpm:
      weight: 1.0
      params:
      - 130.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreGridness16th:
      weight: 3.0
      params:
      - 0.1
      - 7.0
      - 1.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreRhythmicMotifs:
      weight: 1.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: true
  40:
    scoreBpm:
      weight: 3.0
      params:
      - 90.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreGridness16th:
      weight: 2.0
      params:
      - 0.4
      - 7.0
      - 1.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreRhythmicMotifs:
      weight: 0.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: true
  100:
    scoreBpm:
      weight: 3.0
      params:
      - 90.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreGridness16th:
      weight: 3.0
      params:
      - 0.4
      - 7.0
      - 1.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreRhythmicMotifs:
      weight: 3.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: true
