cc: 2
value: 127
funcs:
  scoreMelodicMotifs:
    weight: linear
    params: []
  scoreMeasureForChord:
    weight: linear
    params:
    - none
    - linear
  scoreSimultaneousIntervals:
    weight: linear
    params: []
  scoreTonality:
    weight: linear
    params:
    - none     #family
    - none     #bitmap scale selection 63
steps:
  10:    #NOCHORDS NOMOTIFS  NO INTERVALS 1: LIGHT TONALITY PENTATONIC
    scoreMeasureForChord:
      weight: 0.0
      params:
      - 63.0
      - 0.9
      voices:
      - true
      - true
      - false
      splitVoices: false
    scoreMelodicMotifs:
      weight: 0.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: true
    scoreSimultaneousIntervals:
      weight: 0.0
      params: []
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreTonality:
      weight: 1.0
      params:
      - 3  #pentatonic
      - 4095  #alles aan
      voices:
      - true
      - true
      - true
      splitVoices: false
  20:  #light chords ALLmid ALOWED  LIGHT INTERVALS : TONALITY 2 --> MODAL
    scoreMeasureForChord:
      weight: 1.0
      params:
      - 63.0
      - 0.9
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreMelodicMotifs:
      weight: 0.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: true
    scoreSimultaneousIntervals:
      weight: 0.5
      params: []
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreTonality:
      weight: 2.0
      params:
      - 2 #modal
      - 4095 #alles mag
      voices:
      - true
      - true
      - true
      splitVoices: false
  30:    #light chords all allowed mid   #INTERVALSMID #TONALITY MODAL
    scoreMeasureForChord:
      weight: 1.0
      params:
      - 63.0
      - 0.9
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreMelodicMotifs:
      weight: 0.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: true
    scoreSimultaneousIntervals:
      weight: 0.5
      params: []
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreTonality:
      weight: 3.0
      params:
      - 2 #modal
      - 4095
      voices:
      - true
      - true
      - true
      splitVoices: false
  35: #CHORDS TONAL CORE + OPEN MODAL -- MOTIFS LEAD --INTERVALS MID. TONALITY MAJEUR
    scoreMeasureForChord:
      weight: 1.0
      params:
      - 3.0
      - 1.0
      voices:
      - true
      - true
      - false
      splitVoices: false
    scoreMelodicMotifs:
      weight: 1.0
      params: []
      voices:
      - false
      - false
      - true
      splitVoices: false
    scoreSimultaneousIntervals:
      weight: 1
      params: []
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreTonality:
      weight: 3.0
      params:
      - 0 #majeur
      - 4095
      voices:
      - true
      - true
      - true
      splitVoices: false
  40:  #CHORDS TONAL CORE + OPEN MODAL MOTIFS LEAD + TONALITY MODAL
    scoreMeasureForChord:
      weight: 2.5
      params:
      - 3.0
      - 1.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreMelodicMotifs:
      weight: 1.0
      params: []
      voices:
      - false
      - false
      - true
      splitVoices: false
    scoreSimultaneousIntervals:
      weight: 1
      params: []
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreTonality:
      weight: 3.0
      params:
      - 0 #modal
      - 4095
      voices:
      - true
      - true
      - true
      splitVoices: false
  50: #NO CHORDS , TONALITY RITUAL, MELODIC MOTIFS bas en lead
    scoreMeasureForChord:
      weight: 0.0
      params:
      - 56.0
      - 1.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreMelodicMotifs:
      weight: 2.0
      params: []
      voices:
      - true
      - false
      - true
      splitVoices: true 
    scoreSimultaneousIntervals:
      weight: 0
      params: []
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreTonality:
      weight: 2.0
      params:
      - 15 #ritual
      - 4095
      voices:
      - true
      - true
      - true
      splitVoices: false
  55: #Tonality Africa 
    scoreMeasureForChord:
      weight: 0
      params:
      - 56.0
      - 1.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreMelodicMotifs:
      weight: 1.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreSimultaneousIntervals:
      weight: 0
      params: []
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreTonality:
      weight: 3.0
      params:
      - 23 #africa
      - 4095 
      voices:
      - true
      - true
      - true
      splitVoices: false
  60: #AFRICA STERKE MELODIC 
    scoreMeasureForChord:
      weight: 2.5
      params:
      - 2
      - 1.0
      voices:
      - true
      - true
      - false
      splitVoices: false
    scoreMelodicMotifs:
      weight: 2.0
      params: []
      voices:
      - false
      - false
      - true
      splitVoices: false
    scoreSimultaneousIntervals:
      weight: 0
      params: []
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreTonality:
      weight: 3.0
      params:
      - 23 #africa
      - 4095
      voices:
      - true
      - true
      - true
      splitVoices: false
  70:  #ASIA TONALITY 
    scoreMeasureForChord:
      weight: 0
      params:
      - 56.0
      - 1.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreMelodicMotifs:
      weight: 1.0
      params: []
      voices:
      - false
      - true
      - true
      splitVoices: false
    scoreSimultaneousIntervals:
      weight: 1.0
      params: []
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreTonality:
      weight: 2
      params:
      - 24  #asia
      - 4095
      voices:
      - true
      - true
      - true
      splitVoices: false
  80: #CHORD TENSION AND CLUSTERS ALLES + MOTIFS LEAD + TONAL MAJ/MIN/ALT/WHOLE
    scoreMeasureForChord:
      weight: 2
      params:
      - 48.0
      - 1.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreMelodicMotifs:
      weight: 3.0
      params: []
      voices:
      - false
      - false
      - true
      splitVoices: false
    scoreSimultaneousIntervals:
      weight: 0.0
      params: []
      voices:
      - false
      - false
      - false
      splitVoices: false
    scoreTonality:
      weight: 1.5
      params:
      - 22 #unstable
      - 4095
      voices:
      - true
      - true
      - true
      splitVoices: false
  85: #
    scoreMeasureForChord:
      weight: 1
      params:
      - 48.0
      - 1.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreMelodicMotifs:
      weight: 3.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreSimultaneousIntervals:
      weight: 0
      params: []
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreTonality:
      weight: 2.5
      params:
      - 22  #unstable
      - 4095
      voices:
      - true
      - true
      - true
      splitVoices: false
  90:
    scoreMeasureForChord:
      weight: 0
      params:
      - 48.0
      - 1.0
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreMelodicMotifs:
      weight: 3.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: false
    scoreSimultaneousIntervals:
      weight: 2
      params: []
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreTonality:
      weight: 3.0
      params:
      - 12 #blues
      - 4095
      voices:
      - true
      - true
      - true
      splitVoices: false
  100:
    scoreMeasureForChord:
      weight: 2.0
      params:
      - 36 #rich tertians and clusters
      - 1.0
      voices:
      - false
      - true
      - false
      splitVoices: false
    scoreMelodicMotifs:
      weight: 2.0
      params: []
      voices:
      - true
      - true
      - true
      splitVoices: true
    scoreSimultaneousIntervals:
      weight: 2
      params: []
      voices:
      - false
      - true
      - true
      splitVoices: false
    scoreTonality:
      weight: 3.0
      params:
      - 18 #heptatonic
      - 4095
      voices:
      - true
      - true
      - true
      splitVoices: false